#!/usr/bin/env node
// Генерирует component/src/version.ts из component/package.json.version.
// Запускается в prebuild/postinstall — LUCIDE_VERSION в бандле всегда
// совпадает с опубликованной npm-версией.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const pkgPath = resolve(root, 'package.json');
const out = resolve(root, 'src/version.ts');

const { version } = JSON.parse(readFileSync(pkgPath, 'utf8'));
if (!version) {
  console.error(`sync-version: no version field in ${pkgPath}`);
  process.exit(1);
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/sync-version.mjs — do not edit.\nexport const LUCIDE_VERSION = '${version}'\n`,
);
console.log(`sync-version: wrote ${version} -> src/version.ts`);
