#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const componentPkg = resolve(root, '../component/package.json');
const out = resolve(root, 'src/generated/version.ts');

const { version } = JSON.parse(readFileSync(componentPkg, 'utf8'));
if (!version) {
  console.error(`sync-version: no version field in ${componentPkg}`);
  process.exit(1);
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/sync-version.mjs — do not edit.\nexport const LUCIDE_VERSION = '${version}' as const;\n`,
);
console.log(`sync-version: wrote ${version} -> src/generated/version.ts`);
